set current_user on CreateConferenceJob perform (#14156)
Connects #14144

### Description
Sets `RequestStore.store[:current_user]` before performing the `VirtualHearings::CreateConferenceJob` to prevent the job from failing due to a `NoMethodError (undefined method 'station_id' for nil:NilClass)`