Drop on_hold_duration column (#12964)
Resolves #10896

### Description
Removes the `on_hold_duration` in the task table

### Acceptance Criteria
- [ ] Code compiles correctly

### Testing Plan
1. Migration runs smoothly
```bash
bin/rails db:migrate
```
2. Tasks no longer have the `on_hold_duration` field
```ruby
Task.last.on_hold_duration
NoMethodError: undefined method `on_hold_duration' for #<JudgeDecisionReviewTask:0x00007fc33b35f6c8>
```

### Database Changes
* [x] Query profiling performed (eyeball Rails log, check bullet and fasterer output)
* [x] #appeals-schema notified with summary and link to this PR