Fix NoMethodError for legacy_tasks#index (#7125)
Resolves the `NoMethodError app/controllers/legacy_tasks_controller.rb in index: undefined method `downcase' for nil:NilClassruby` errors we've been seeing (example here: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2341/). This was caused by trying to call `downcase()` on a nil value.