other_close_event_date no longer fails on nil last_synced_at (#16142)
This is a fairly common error showing up in Sentry.

```
NoMethodError: undefined method `to_date' for nil:NilClass
  from app/models/supplemental_claim.rb:53:in `other_close_event_date'
  from app/models/appeal_events.rb:144:in `sc_other_close_event'
  from app/models/appeal_events.rb:46:in `sc_events'
  from app/models/appeal_events.rb:14:in `all'
  from app/models/supplemental_claim.rb:57:in `events'
```

![Screen Shot 2021-04-19 at 11 48 16 AM](https://user-images.githubusercontent.com/314663/115265475-446f8600-a105-11eb-8354-7e9b9b53770b.png)

`SupplementalClaim#other_close_event_date` tries to return `end_product_establishments.first.last_synced_at.to_date` but `last_synced_at` isn't always present.

It is not clear to me if this is causing user-facing errors or is just noise in the logs, but might as well fix it either way!

### Acceptance Criteria
- [ ] Test passes

### Testing Plan
1. Run the new test.