set current_user on DeleteConferencesJob perform (#14160)
Connects #14144 

### Description
Sets `RequestStore.store[:current_user]` before performing the `VirtualHearings::DeleteConferencesJob` to prevent the job from failing due to a `NoMethodError (undefined method 'station_id' for nil:NilClass)`