Disable RO dropdown on edit docket (#16888)
Resolves [CASEFLOW-2511](https://vajira.max.gov/browse/CASEFLOW-2511)

### Description
The regional office dropdown needs to be disabled if there are hearings scheduled

### Acceptance Criteria
Expected behavior: when editing a hearing day, the RO field can only be changed if the docket does not have any scheduled hearings.
Exception: if the docket type = Central, the RO field cannot be changed
Observed behavior: the RO field is editable even when there are scheduled hearings on the docket