🔧 Add Zeitwerk inflector for `AMOMetricsReportJob`
Resolves `NameError: uninitialized constant AMOMetricsReportJob`.

The input of the Zeitwerk autoloader is the file system.
Given the file `amo_metrics_report_job.rb`, Zeitwerk invokes camelize on `amo_metrics_report_job`,
which yields `AmoMetricsReportJob`, and expects the file to define the constant `AmoMetricsReportJob`.
That is what the error message says.

  NameError: uninitialized constant AMOMetricsReportJob
    Did you mean?  AmoMetricsReportJob

One way to fix this is to tell the Zeitwerk inflector about this acronym.