Don't throw error when validating nil doc id (#14443)
Resolves `NoMethodError: undefined method `match?' for nil:NilClass` for acting judges

### Description
Some doc ids are nil. Do not try to validate nil document ids. Also, on occasion, we have a nil work product (about 1% of decass records) If this work product is nil, validate the document id on all matchers.

### Testing Plan
1. On master
```ruby
appeal = LegacyAppeal.last
VACOLS::Decass.where(defolder: appeal.vacols_id).update_all(dedocid: nil)
appeal.reload.vacols_case_review.document_id
=> nil
appeal.reload.vacols_case_review.valid_document_id?
NoMethodError: undefined method `match?' for nil:NilClass
```
1. Pull this branch
```ruby
reload!
appeal = LegacyAppeal.last
appeal.reload.vacols_case_review.document_id
=> nil
appeal.reload.vacols_case_review.valid_document_id?
=> false
```